trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'P2Folder/AngularGameBook'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  displayName: sonarclour prepare
  inputs:
    SonarCloud: 'SonarcloudAngular'
    organization: 'project2-gamebook'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Project2-GameBook_AngularGameBook'
    cliProjectName: 'AngularGameBook'
    cliSources: '$(solution)/src'
    extraProperties: 'sonar.javascript.lcov.reportPaths=$(solution)/coverage/AngularGameBook/lcov.info'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
    
# - task: Npm@1
#   displayName: 'NPM Test'
#   inputs:
#     command: 'custom'
#     workingDir: $(solution)
#     customCommand: 'run test-headless'

- task: SonarCloudAnalyze@1
  displayName: 'SonarCloud Analyze'

- task: SonarCloudPublish@1
  displayName: 'SonarCloud Publish'
  inputs:
    pollingTimeoutSec: '300'