trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarcloudAngular'
    organization: 'project2-gamebook'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Project2-GameBook_AngularGameBook'
    cliProjectName: 'AngularGameBook'
    cliSources: '.'
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build-prod'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run test-headless'
- task: SonarCloudAnalyze@1
  displayName: 'SonarCloud Analyze'

- task: SonarCloudPublish@1
  displayName: 'SonarCloud Publish'
  inputs:
    pollingTimeoutSec: '300'